[package]
name = "opr-tests"
version = "0.1.0"
edition = "2021"

[build-dependencies]
opr-test-data = { path = "../opr-test-data" }

[dev-dependencies]
opr = { path = "../opr" }
rstest = { version = ">= 0.18.0, < 0.26", default-features = false }
serde_json = "1.0"
